spring:
  datasource:
    driver-class-name: <MySQL기준> com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ <스키마이름> ?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: <데이터베이스 접근 비밀번호>

# sql 쿼리출력하기
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

